export const quipList = [
	"Charging up the flavor boosters, please hold",
	"Cooking up some pixel perfection, just for you",
	"Gathering the best dishes from the digital universe",
	"Loading the fun and removing the calories",
	"Reticulating splines for optimal menu satisfaction",
	"Serving up a buffet of pixels, just a few seconds more",
	"Adjusting the virtual napkins, almost ready to feast your eyes",
	"Mixing and matching the bits and bytes for your viewing pleasure",
	"Just flipping the digital pancakes, hold tight!",
	"Sifting through a digital cookbook for the finest offerings",
	"Dusting off the pixels and polishing the interface",
	"Stirring up a digital storm, your menu is on its way",
	"Preparing a visual treat, piping hot and fresh from the server",
	"Whipping up a virtual storm for your epicurean delight",
	"Seasoning the pixels with a dash of magic, almost there!",
	"Arranging the visual feast, almost ready for your indulgence",
	"Creating a visual symphony that'll make your taste buds dance",
	"Simmering the pixels to perfection, just a moment longer",
	"Plating the digital delights, almost ready to serve",
	"Hold tight! We're chopping, dicing, and sorting the menu for you",
	"Savoring the anticipation? We're plating your options just right!",
	"Stirring the bits and bytes to serve you the finest menu. Please wait warmly",
	"We're prepping your digital buffet. Just a sprinkle of loading time left!",
	"Marinating the app with the finest sauce. Almost ready!",
];
